version: "3.8"

services:
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /volumes:/volumes
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

networks:
    docker-net:
        name: docker-net
        external: false

