version: "3.8"

services:
    rundeck:
        image: rundeck/rundeck:5.0.1-rc1-20240103
        environment:
            RUNDECK_GRAILS_URL: https://0.0.0.0:4440/
        volumes:
            - rundeck:/home/rundeck/server/data:rw
        networks:
            - docker-net
        ports:
            - 4440:4440

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    rundeck:
        external: false
