version: "3.8"

services:

    keycloak:
        image: jboss/keycloak
        restart: on-failure:3
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
        ports:
            - 8080:8080
        networks:
            - docker-net

networks:
    docker-net:
        name: docker-net
        external: false
