version: "3.8"

services:

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        hostname: nginx-proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks: 
            - docker-net

    nodo1:
        image: httpd
        container_name: httpd
        environment:
            - VIRTUAL_HOST=nodo1.localhost
            - VIRTUAL_PORT=80
        expose:
            - 80
        networks: 
            - docker-net

networks:
    docker-net:
    
