version: "3.8"

services:
    db2:
        image: ibmcom/db2:11.5.0.0
        restart: on-failure:3
        privileged: true
        env_file:
            - ./docker-env/db2.env
        volumes:
            - db2:/database:rw
        networks:
            - docker-net
        ports:
            - 50000:50000

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    db2:
        external: false
