global:
  scrape_interval: 15s 
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'scale_data'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['pushgateway:9091']
    honor_labels: true
