bind 127.0.0.1
port 7001

requirepass "redis"
masterauth "redis"

protected-mode no
appendonly yes

replica-priority 50

min-replicas-to-write 1
min-replicas-max-lag 10

# Habilitar el modo Clúster
# cluster-enabled yes
# cluster-config-file nodes.conf
# cluster-node-timeout 5000
