version: "3.8"

services:
  plex:
    hostname: plex
    container_name: plex
    image: linuxserver/plex:1.32.4
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Argentina/Buenos_Aires
      VERSION: docker
    ports:
      - 32400:32400
    volumes:
      - ./media:/media:Z
      - plex:/config
    networks:
      - docker-net

networks:
  docker-net:
    name: docker-net
    external: false

volumes:
  plex:
    name: plex
    external: false
