version: "3.8"

services:
    postwoman:
        image: liyasthomas/postwoman:latest
        restart: on-failure:3
        env_file:
            - ./docker-env/postwoman.env
        networks:
            - docker-net
        ports:
            - 3000:3000

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    postwoman:
        external: false
