version: "3.8"

services:

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 80:80
            - 81:81
            - 82:82
            - 83:83
        networks: 
            - docker-net
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw


    nodo1:
        image: nginx:alpine
        container_name: nodo1
        expose: 
            - 80
        networks: 
            - docker-net
        command: /bin/sh -c "echo nodo1 > /usr/share/nginx/html/index.html && nginx-debug -g 'daemon off;'"


    nodo2:
        image: nginx:alpine
        container_name: nodo2
        expose: 
            - 80
        networks: 
            - docker-net
        command: /bin/sh -c "echo nodo2 > /usr/share/nginx/html/index.html && nginx-debug -g 'daemon off;'"


networks:
    docker-net:
        name: docker-net
        external: false
     
