version: "3.8"

services:

  jaeger:
    container_name: jaeger
    hostname: jaeger
    image: jaegertracing/all-in-one:1.57
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 9411:9411
      - 14268:14268
    networks:
      - docker-net


networks:
  docker-net:
    name: docker-net
    external: false
