upstream nginx_upstream {
    server nodo-1:80 weight=2;
    server nodo-2:80;
}

server {
    server_name nginx_server;
    listen 80;
    location / {
        proxy_set_header Host prueba.com;
        proxy_pass http://prueba.com;
    }
}
