version: "3.8"

services:

    minio:
        image: minio/minio
        restart: on-failure:3

        env_file: 
            - ./docker-env/minio.env

        volumes:
            - ~/volumes/minio/data:/data

        ports:
            - 9000:9000

        command: server /data