version: "3.8"

services:
    portainer:
        image: dannyben/madness:0.9.3
        restart: on-failure:3
        env_file:
            - ./docker-env/madness.env
        volumes:
            - ./volumes/madness/data:/docs:rw
        networks:
            - docker-net
        ports:
            - 3000:3000

networks:
    docker-net:
        name: docker-net
        external: false

