bind 127.0.0.1
port 5003

requirepass "redis"
masterauth "redis"

sentinel announce-ip "127.0.0.1"
sentinel announce-port 5003
sentinel resolve-hostnames yes
sentinel sentinel-pass "redis"

# server1
sentinel monitor server1 127.0.0.1 7001 2
sentinel auth-pass server1 "redis"
sentinel down-after-milliseconds server1 3000
sentinel failover-timeout server1 6000
sentinel parallel-syncs server1 1
