version: "3.8"

services:
    greenplum:
        image: datagrip/greenplum:latest
        restart: on-failure:3
        env_file:
            - ./docker-env/greenplum.env
        volumes:
            - greenplum:/gpdata:rw
        ports:
            - 5432:5432

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    greenplum:
        external: false
