version: "3.8"

services:

    konga:
        container_name: konga
        image: pantsel/konga
        environment:
            NODE_ENV: production # or development
            TOKEN_SECRET: token
        networks:
            - docker-net
        ports:
            - 1337:1337
        depends_on:
            - "kong"

    kong:
        container_name: kong
        image: kong
        environment:
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
            KONG_DATABASE: postgres
            KONG_PG_HOST: postgres
            KONG_PG_PASSWORD: kong
            KONG_CASSANDRA_CONTACT_POINTS: postgres
        networks:
            - docker-net
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
            - 8444:8444
        depends_on:
            - "postgres"
            - "db-init"

    db-init:
        container_name: db-init
        image: kong
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: postgres
            KONG_PG_PASSWORD: kong
            KONG_CASSANDRA_CONTACT_POINTS: postgres
        networks:
            - docker-net
        depends_on:
            - "postgres"
        command: kong migrations bootstrap

    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: kong
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: kong
        volumes:
            - postgres:/var/lib/postgresql/data:rw
        networks:
            - docker-net
        ports:
            - 5432:5432
        healthcheck:
            start_period: 5s

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    postgres:
