version: "3.8"

services:

    python:
        image: python:3.9-alpine
        container_name: python39-dev
        tty: true
        volumes:
            - ./:/usr/src/app/
        ports:
            - 5000:5000