version: "3.8"

services:
    jenkins:
        image: jenkins/jenkins:latest
        volumes:
            - jenkins:/var/jenkins_home:rw
        networks:
            - docker-net
        ports:
            - 8080:8080
            - 50000:50000

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    jenkins:
        external: false
