version: "3.8"

services:

    jenkins:
        image: jenkins/jenkins:lts
        restart: on-failure:3
        user: root
        env_file: 
            - ./docker-env/jenkins.env

        volumes:
            - ~/volumes/jenkins:/var/jenkins_home:rw

        ports:
            - "10000:8080"
            - "50000:50000"
