version: "3.8"

services:
    jenkins:
        image: jenkins/jenkins:lts
        restart: on-failure:3
        user: root
        env_file:
            - ./docker-env/jenkins.env
        volumes:
            - jenkins:/var/jenkins_home:rw
        networks:
            - docker-net
        ports:
            - 8080:8080
            - 50000:50000

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    jenkins:
        external: false
