version: "3.8"

services:
    mongodb:
        image: mongo:4.2.3
        restart: on-failure:3
        env_file:
            - ./docker-env/mongodb.env
        volumes:
            - mongodb:/data/db
        networks:
            - docker-net
        ports:
            - 27017:27017

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    mongodb:
        external: false
