version: "3.8"

services:
    neo4j:
        image: neo4j:4.0.3
        restart: on-failure:3
        env_file:
            - ./docker-env/neo4j.env
        volumes:
            - neo4j:/data:rw
        ports:
            - 7474:7474
            - 7687:7687

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    neo4j:
        external: false
