version: "3.8"

services:

  sonar:
    container_name: sonar
    image: sonarqube:community
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - 9000:9000
    networks:
      - docker-net
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_DB: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - docker-net
    ports:
      - 5432:5432
    healthcheck:
      start_period: 6s

networks:
  docker-net:
    name: docker-net
    external: false

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres:
