version: "3.8"

services:
    portainer:
        image: thomsch98/markserv:0.1.0-rc-alpine
        restart: on-failure:3
        env_file:
            - ./docker-env/madness.env
        volumes:
            - ./volumes/markserv/data:/data:rw
        networks:
            - docker-net
        ports:
            - 3080:3080

networks:
    docker-net:
        name: docker-net
        external: false

