version: "3.8"

services:
    redis:
        image: redis:5.0.7
        restart: on-failure:3
        env_file:
            - ./docker-env/redis.env
        volumes:
            - redis:/data:rw
        networks:
            - docker-net
        ports:
            - 6379:6379
        command: redis-server --appendonly yes

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    redis:
        external: false
