name: atheos

volumes:
  atheos:
    name: atheos
    external: false

networks:
  docker-net:
    name: docker-net
    external: true

services:
  atheos:
    image: atheos/atheos-ce:2.30.1
    container_name: atheos
    hostname: atheos
    restart: always
    volumes:
      - atheos:/var/www/html/workspace/
    expose:
      - 80
    networks:
      - docker-net
