# VARS
# ----------------------------------------
APP_NAME=app



# SRC
# ----------------------------------------
install:
	@go mod init $(APP_NAME)
	@go get -d


build:
	@go build

run:
	@printf "Run $(APP_NAME)"
	@./$(APP_NAME)