version: "3.8"

services:
  jdownloader:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader
    hostname: jdownloader
    volumes:
      - ./output:/output:rw
      - jdownloader:/config:rw
    networks:
      - docker-net
    ports:
      - 5800:5800

networks:
  docker-net:
    name: docker-net
    external: true

volumes:
  jdownloader:
    name: jdownloader
    external: false
