version: "3.8"

services:

    consul:
        image: consul:1.9.9
        restart: on-failure:3
        volumes:
            - consul:/consul:rw
        networks:
            - docker-net
        ports:
            - 80:8500
            - 8600:8600/udp
        command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0

    ser1:
        image: python:3.9-alpine
        depends_on:
            - consul
        restart: on-failure:3
        working_dir: /usr/src/app
        volumes:
            - ./python:/usr/src/app:rw
        networks:
            - docker-net
        ports:
            - 90:5000
        command: /bin/sh -c "pip install -r requirements.txt && python app.py ser1 5000"

    ser2:
        image: python:3.9-alpine
        depends_on:
            - consul
        restart: on-failure:3
        working_dir: /usr/src/app
        volumes:
            - ./python:/usr/src/app:rw
        networks:
            - docker-net
        ports:
            - 91:5000
        command: /bin/sh -c "pip install -r requirements.txt && python app.py ser2 5000"

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    consul:
        external: false
