services:
  mongo:

    image: mongo:7
    container_name: dartvader-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: dart_pub
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"

  dartvader:
    build:
      context: ./dartvader
      dockerfile: Dockerfile
    container_name: dartvader
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      UNPUB_MONGO_URI: mongodb://mongo:27017/dart_pub
    command:
      - --host
      - 0.0.0.0
      - --port
      - "4000"
      - --database
      - mongodb://mongo:27017/dart_pub
    ports:
      - "4000:4000"
    volumes:
      - dartvader:/app/dartvader-packages

volumes:
  mongo:
  dartvader:
