name: minio

networks:
  docker-net:
    name: docker-net
    external: true

volumes:
  minio:
    name: minio
    external: false

services:
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    restart: on-failure:3
    environment:
      - MINIO_ACCESS_KEY=adminminio
      - MINIO_SECRET_KEY=adminminio
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
