version: "3.8"

services:
    portainer:
        image: portainer/portainer-ce:2.20.3
        container_name: portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - portainer:/data:rw
        networks:
            - docker-net
        ports:
            - 9000:9000
            - 8000:8000

networks:
    docker-net:

volumes:
    portainer:
