version: "3.8"

services:

    vault:
        container_name: vault
        hostname: vault
        image: vault:1.13.3
        volumes:
            - ./config.hcl:/vault/config/config.hcl
            - vault:/vault/file/
        environment:
            - VAULT_ADDR=http://0.0.0.0:8200
        ports:
            - 8200:8200
        cap_add:
            - IPC_LOCK
        command: server

    vault-init:
        image: vault:1.13.3
        container_name: vault-init
        environment:
            - VAULT_ADDR=http://vault:8200
            - MY_VAULT_TOKEN=${MY_VAULT_TOKEN:-admin}
        volumes:
            - ./vault-init.sh:/usr/local/bin/vault-init.sh
            - vault:/vault/file/
        command: /usr/local/bin/vault-init.sh
        depends_on:
            - vault

volumes:
    vault: